---
apiVersion: flux.kluctl.io/v1alpha1
kind: KluctlDeployment
metadata:
  name: "{{ target.targetConfig.ref }}"
  namespace: dynamic
spec:
  interval: 5m
  path: "./flux/apps/product-team"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m
  prune: true
  target: "{{ target.targetConfig.ref }}"
  renameContexts:
  - oldContext: default
    newContext: rancher-desktop
