targets:
- name: "{{ target.targetConfig.ref }}"
  context: rancher-desktop
  dynamicArgs:
  - name: environment
  - name: file
  targetConfig:
    project:
      url: https://github.com/gitbluf/gitops-config.git
    refPattern: master
    file: dynamic/dynamic.yaml