---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ service }}
  namespace: {{ args.environment }}
spec:
  interval: 5m
  chart:
    spec:
      chart: {{ service }}
      version: {{ chart_version }}
      sourceRef:
        kind: HelmRepository
        name: {{ chart }}
        namespace: {{ args.environment }}
      interval: 1m
  targetNamespace: {{ args.environment }}
  values: |
    {{ values }}
