---
apiVersion: flux.kluctl.io/v1alpha1
kind: KluctlDeployment
metadata:
  name: product-team
  namespace: dev
spec:
  interval: 5m
  path: "./flux/apps/product-team"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m
  prune: true
  target: dev

---
apiVersion: flux.kluctl.io/v1alpha1
kind: KluctlDeployment
metadata:
  name: product-team
  namespace: prod
spec:
  interval: 5m
  path: "./flux/apps/product-team"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 2m
  prune: true
  target: prod
