---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: microservices-helm
  namespace: wego-system
spec:
  chart:
    spec:
      chart: ./deploy/kubernetes/helm-chart
      sourceRef:
        kind: GitRepository
        name: microservices-helm
  interval: 5m0s
  targetNamespace: sock-shop

